In [8]:
import numpy as np
import random
from itertools import product
import contextlib
from Environment import * 
from Tabular_Model_Based_Algos import *
from Tabular_Model_Free_Algos import * 
from Non_Tabular_Model_Free_Algos import *

In [2]:
# Configures numpy print options
@contextlib.contextmanager
def _printoptions(*args, **kwargs):
    original = np.get_printoptions()
    np.set_printoptions(*args, **kwargs)
    try:
        yield
    finally:
        np.set_printoptions(**original)

# Tabular Model Based Algorithms

## Policy iteration

In [5]:
policy, values = policy_iteration(env, gamma, theta, max_iterations)
env.render(policy, values)

## Policy iteration
Lake:
[['&' '.' '.' '.']
 ['.' '#' '.' '#']
 ['.' '.' '.' '#']
 ['#' '.' '.' '$']]
Policy:
[['↓' '→' '↓' '←']
 ['↓' '↑' '↓' '↑']
 ['→' '↓' '↓' '↑']
 ['↑' '→' '→' '↑']]
Value:
[[0.455 0.504 0.579 0.505]
 [0.508 0.    0.653 0.   ]
 [0.584 0.672 0.768 0.   ]
 [0.    0.771 0.887 1.   ]]


## Value iteration

In [9]:
optimal_policy, values = value_iteration(env, gamma, theta, max_iterations)
env.render(optimal_policy, values)

Lake:
[['&' '.' '.' '.']
 ['.' '#' '.' '#']
 ['.' '.' '.' '#']
 ['#' '.' '.' '$']]
Policy:
[['↓' '→' '↓' '←']
 ['↓' '↑' '↓' '↑']
 ['→' '↓' '↓' '↑']
 ['↑' '→' '→' '↑']]
Value:
[[0.455 0.504 0.579 0.505]
 [0.508 0.    0.653 0.   ]
 [0.584 0.672 0.768 0.   ]
 [0.    0.771 0.887 1.   ]]


# Tabular Model Free Algorithms

## SARSA

In [10]:
policy, value = sarsa(env, max_episodes, eta, gamma, epsilon, seed=seed)
env.render(policy, value)

Lake:
[['&' '.' '.' '.']
 ['.' '#' '.' '#']
 ['.' '.' '.' '#']
 ['#' '.' '.' '$']]
Policy:
[['↓' '←' '↓' '←']
 ['↓' '↑' '↓' '↑']
 ['→' '↓' '↓' '↑']
 ['↑' '→' '→' '↑']]
Value:
[[0.449 0.371 0.374 0.256]
 [0.5   0.    0.601 0.   ]
 [0.578 0.67  0.776 0.   ]
 [0.    0.769 0.893 1.   ]]


## Q-Learning Run

In [11]:
policy, value = q_learning(env, max_episodes, eta, gamma, epsilon, seed=seed)
env.render(policy, value)

Lake:
[['&' '.' '.' '.']
 ['.' '#' '.' '#']
 ['.' '.' '.' '#']
 ['#' '.' '.' '$']]
Policy:
[['↓' '→' '↓' '←']
 ['↓' '↑' '↓' '↑']
 ['→' '↓' '↓' '↑']
 ['↑' '→' '→' '↑']]
Value:
[[0.46  0.485 0.568 0.509]
 [0.515 0.    0.636 0.   ]
 [0.593 0.679 0.752 0.   ]
 [0.    0.765 0.89  1.   ]]


# Non Tabular Model Free Algorithms

## Linear SARSA

In [12]:
parameters = linear_sarsa(linear_env, max_episodes, eta, gamma, epsilon, seed=seed)
policy, value = linear_env.decode_policy(parameters)
linear_env.render(policy, value)

Lake:
[['&' '.' '.' '.']
 ['.' '#' '.' '#']
 ['.' '.' '.' '#']
 ['#' '.' '.' '$']]
Policy:
[['↓' '→' '↓' '←']
 ['↓' '↑' '↓' '↑']
 ['→' '→' '↓' '↑']
 ['↑' '→' '→' '↑']]
Value:
[[0.442 0.473 0.554 0.46 ]
 [0.498 0.    0.666 0.   ]
 [0.573 0.672 0.767 0.   ]
 [0.    0.789 0.887 1.   ]]


## Linear Q-Learning

In [13]:
parameters = linear_q_learning(linear_env, max_episodes, eta, gamma, epsilon, seed=seed)
policy, value = linear_env.decode_policy(parameters)
linear_env.render(policy, value)

Lake:
[['&' '.' '.' '.']
 ['.' '#' '.' '#']
 ['.' '.' '.' '#']
 ['#' '.' '.' '$']]
Policy:
[['↓' '←' '←' '←']
 ['↓' '↑' '↓' '↑']
 ['→' '↓' '↓' '↑']
 ['↑' '→' '→' '↑']]
Value:
[[0.451 0.404 0.353 0.282]
 [0.508 0.    0.657 0.   ]
 [0.585 0.672 0.758 0.   ]
 [0.    0.773 0.884 1.   ]]
